### ISSUE TITLE
yaml-cpp always required, but build fails if using --with-yaml

### ISSUE THREAD

**Issue by ryandesign** [Velocidex/c-aff4#16]
If I configure the latest c-aff4 with `--with-yaml` (I have yaml-cpp 0.6.2 installed), the build fails with:

```
In file included from data_store.cc:32:
In file included from /opt/local/include/yaml-cpp/yaml.h:13:
In file included from /opt/local/include/yaml-cpp/stlemitter.h:12:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/set:398:40: error: no template named 'less'; did you mean '::std::less'?
template <class _Key, class _Compare = less<_Key>,
                                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__functional_base:57:29: note: '::std::less' declared here
struct _LIBCPP_TEMPLATE_VIS less : binary_function<_Tp, _Tp, bool>
                            ^
```

(followed by lots of other errors)

If I do not use `--with-yaml`, then the build succeeds, but yaml-cpp is still required at build time, and osxpmem does end up linked with the yaml-cpp library.

**Comment by scudette** [comment]
Yes I think the yaml code is not used now. We can just remove the dependency and delete it.

**Comment by scudette** [comment]
I think the yaml dependency is needed for pmem tools but not for aff4 itself. I think cpp-yaml as distributed in ubuntu is too old (not c++11 support) so we need to latest git head to make it work.

**Comment by jtsylve** [comment]
Is there a configure option to only build aff4 and not the tools?

**Comment by scudette** [comment]
No I don't think there is an option although you can just run make install
in the aff4 directory to just built the aff4 portion?

**Comment by scudette** [comment]
build issues are fixed now by using docker compose.
