### ISSUE TITLE
Makefile:496: ../../aff4/.deps/linpmem-compatibility.Po: No such file or directory

### ISSUE THREAD

**Issue by grassy** [Velocidex/c-aff4#18]
I am trying to build pmem static libraries on Ubuntu17.10 again, but also occurs error.

Making install in aff4
make[1]: Entering directory '/home/meimei/c-aff4/aff4'
make[2]: Entering directory '/home/meimei/c-aff4/aff4'
 /bin/mkdir -p '/home/meimei/static/lib'
 /bin/mkdir -p '/home/meimei/static/include/aff4/'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libaff4.la '/home/meimei/static/lib'
 /usr/bin/install -c -m 644 aff4_base.h aff4_image.h aff4_io.h aff4_simple.h config.h lexicon.h lexicon.inc rdf.h aff4_errors.h aff4_init.h aff4_registry.h aff4_utils.h data_store.h libaff4.h zip.h aff4_map.h tclap_parsers.h aff4_directory.h aff4_imager_utils.h aff4_file.h aff4_symstream.h libaff4-c.h threadpool.h '/home/meimei/static/include/aff4/'
libtool: install: /usr/bin/install -c .libs/libaff4.lai /home/meimei/static/lib/libaff4.la
libtool: install: /usr/bin/install -c .libs/libaff4.a /home/meimei/static/lib/libaff4.a
libtool: install: chmod 644 /home/meimei/static/lib/libaff4.a
libtool: install: ranlib /home/meimei/static/lib/libaff4.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /home/meimei/static/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/meimei/static/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/meimei/static/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c aff4imager '/home/meimei/static/bin'
libtool: install: /usr/bin/install -c aff4imager /home/meimei/static/bin/aff4imager
make[2]: Leaving directory '/home/meimei/c-aff4/aff4'
make[1]: Leaving directory '/home/meimei/c-aff4/aff4'
Making install in tools/pmem
make[1]: Entering directory '/home/meimei/c-aff4/tools/pmem'
Makefile:496: ../../aff4/.deps/linpmem-compatibility.Po: No such file or directory
make[1]: *** No rule to make target '../../aff4/.deps/linpmem-compatibility.Po'.  Stop.
make[1]: Leaving directory '/home/meimei/c-aff4/tools/pmem'
Makefile:465: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

../../aff4/.deps has files:
total 560
-rw-r--r-- 1 root root 29062 Mar 31 23:01 aff4_directory.Plo
-rw-r--r-- 1 root root 28275 Mar 31 23:01 aff4_file.Plo
-rw-r--r-- 1 root root 29286 Mar 31 23:00 aff4_image.Plo
-rw-r--r-- 1 root root 32628 Mar 31 23:01 aff4imager.Po
-rw-r--r-- 1 root root 34645 Mar 31 23:01 aff4_imager_utils.Plo
-rw-r--r-- 1 root root    83 Mar 31 22:59 aff4_init.Plo
-rw-r--r-- 1 root root 28914 Mar 31 23:01 aff4_map.Plo
-rw-r--r-- 1 root root 28113 Mar 31 23:01 aff4_symstream.Plo
-rw-r--r-- 1 root root  2758 Mar 31 23:01 compatibility.Po
-rw-r--r-- 1 root root 28973 Mar 31 23:00 data_store.Plo
-rw-r--r-- 1 root root 26788 Mar 31 23:00 lexicon.Plo
-rw-r--r-- 1 root root 28961 Mar 31 23:01 libaff4-c.Plo
-rw-r--r-- 1 root root 30226 Mar 31 23:00 libaff4.Plo
-rw-r--r-- 1 root root 27211 Mar 31 23:00 rdf.Plo
-rw-r--r-- 1 root root 19377 Mar 31 23:01 tclap_parsers.Plo
-rw-r--r-- 1 root root 30135 Mar 31 23:00 zip.Plo

Thanks a lot.

**Comment by scudette** [comment]
There may be some bug in the automake file. Maybe just remove the compatibility altogether - its only used to make the imager run on really old versions of linux.

**Comment by scudette** [comment]
Just to be more specific:
```
--- a/aff4/Makefile.am
+++ b/aff4/Makefile.am
@@ -94,7 +94,7 @@ aff4imager_LDFLAGS = $(STATIC_LINKERLDFLAGS)

 # Linux backwards compatibility shims for static builds.
 if LINUX
-   aff4imager_SOURCES = aff4imager.cc compatibility.cc
+   aff4imager_SOURCES = aff4imager.cc 
 else
    aff4imager_SOURCES = aff4imager.cc
 endif
--- a/tools/pmem/Makefile.am
+++ b/tools/pmem/Makefile.am
@@ -50,7 +50,8 @@ if LINUX
 bin_PROGRAMS = linpmem
 linpmem_LDFLAGS = $(STATIC_LINKERLDFLAGS)
 linpmem_CXXFLAGS = -std=c++11 -g -Wall -O0
-linpmem_SOURCES = pmem_imager.cc linux_pmem.cc $(top_srcdir)/aff4/compatibility.cc
+linpmem_SOURCES = pmem_imager.cc linux_pmem.cc
```

**Comment by grassy** [comment]
Thank you very much. It works for me.
