### ISSUE TITLE
Logical imaging issue using find - flat file output only

### ISSUE THREAD

**Issue by hoyt-harness** [Velocidex/c-aff4#19]
System: Linux Mint 18 Cinnamon 64-bit
Kernel: Linux 4.4.0-119-generic

I have a test directory (.../testdir/...) located in the same directory as linpmem. Running this command:
`find ./testdir -type f`
...results in this:
`./testdir/subdir1/.hiddendir1/.hiddendir11/fileh111.txt
./testdir/subdir1/.hiddendir1/fileh11.txt
./testdir/subdir1/.hiddendir1/subdir11/file111.txt
./testdir/subdir1/file1.txt
./testdir/subdir2/.hiddendir2/subdir21/file211.txt
./testdir/subdir2/.hiddendir2/fileh21.txt
./testdir/subdir2/.hiddendir2/.hiddendir21/fileh211.txt
./testdir/subdir2/file2.txt
./testdir/file.txt
./testdir/subdir3/file3.txt
./testdir/subdir3/.hiddendir3/fileh31.txt
./testdir/subdir3/.hiddendir3/subdir31/file311.txt
./testdir/subdir3/.hiddendir3/.hiddendir31/fileh311.txt`
...which is correct.

Running this command:
`find ./testdir -type f | linpmem -i @ -o ./img_logical.aff4`
...results in a flat text file with zero bytes named "img_logical.aff4":
`$ shed --hex img_logical.aff4 
shed: img_logical.aff4 has zero size`

**Comment by hoyt-harness** [comment]
Debugging messages:

$ find ./testdir -type f | linpmem -d -i @ -o ./img_logical.aff4
I0417 17:09:53.971830 13606 aff4_file.cc:59] Creating intermediate directories //
I0417 17:09:53.971854 13606 aff4_file.cc:59] Creating intermediate directories //home/
I0417 17:09:53.971869 13606 aff4_file.cc:59] Creating intermediate directories //home/hharness/
I0417 17:09:53.971884 13606 aff4_file.cc:59] Creating intermediate directories //home/hharness/dev/
I0417 17:09:53.971899 13606 aff4_file.cc:59] Creating intermediate directories //home/hharness/dev/1_test/
I0417 17:09:53.971912 13606 aff4_file.cc:283] Opening file /home/hharness/dev/1_test/img_logical.aff4
I0417 17:09:53.971990 13606 data_store.h:491] AFF4FactoryOpen (new instance): file:///home/hharness/dev/1_test/img_logical.aff4
I0417 17:09:53.972064 13606 data_store.cc:614] URN file:///home/hharness/dev/1_test/img_logical.aff4 is already in use.
I0417 17:09:53.972074 13606 data_store.h:449] AFF4FactoryOpen (cached): file:///home/hharness/dev/1_test/img_logical.aff4
I0417 17:09:53.972101 13606 data_store.h:317] Returning: file:///home/hharness/dev/1_test/img_logical.aff4
I0417 17:09:53.972115 13606 data_store.h:491] AFF4FactoryOpen (new instance): aff4://69bb1e36-8dc6-4fb5-8bef-8f7205b321db
Creating output AFF4 ZipFile.
I0417 17:09:53.972141 13606 data_store.h:317] Returning: aff4://69bb1e36-8dc6-4fb5-8bef-8f7205b321db
I0417 17:09:53.972151 13606 data_store.h:317] Returning: file:///home/hharness/dev/1_test/img_logical.aff4
I0417 17:09:53.972162 13606 data_store.h:449] AFF4FactoryOpen (cached): aff4://69bb1e36-8dc6-4fb5-8bef-8f7205b321db
I0417 17:09:53.972179 13606 data_store.h:317] Returning: aff4://69bb1e36-8dc6-4fb5-8bef-8f7205b321db

**Comment by scudette** [comment]
I wonder if you are using the correct version of linpmem? 

```
$ ./linpmem --version

./linpmem  version: 3.0.rc1
```

This is what I did:
```
$ wget https://github.com/Velocidex/c-aff4/releases/download/1.0.rc1/linpmem
$ chmod  +x linpmem
$ find /bin/ | ./linpmem -i @ -o /tmp/test.aff4 -dd -t
2018-04-18 06:27:34 I Adding /bin/ as file:///bin/
2018-04-18 06:27:34 E Unable to find storage for AFF4Directory file:///bin/
2018-04-18 06:27:34 E Unable to find file:///bin/
2018-04-18 06:27:34 I Adding /bin/nano as file:///bin/nano
2018-04-18 06:27:34 W Output file file:///tmp/test.aff4 will be truncated.
2018-04-18 06:27:34 I Creating output AFF4 ZipFile.
2018-04-18 06:27:34 I Adding /bin/dir as file:///bin/dir
2018-04-18 06:27:34 I Adding /bin/run-parts as file:///bin/run-parts
2018-04-18 06:27:34 I Adding /bin/pidof as file:///bin/pidof
2018-04-18 06:27:34 I Adding /bin/sleep as file:///bin/sleep
2018-04-18 06:27:34 I Adding /bin/bzdiff as file:///bin/bzdiff
...
2018-04-18 06:27:34 I Adding /bin/mt-gnu as file:///bin/mt-gnu
2018-04-18 06:27:34 I Adding /bin/gunzip as file:///bin/gunzip
2018-04-18 06:27:34 I Writing Centeral Directory for 127 members.
```

I suppose if you are using an older linpmem which does not understand the special @ filename it would be trying to add a literal file called "@" which does not exist so it would create an empty volume.

**Comment by hoyt-harness** [comment]
I think that's exactly the issue:

  `$ ./linpmem --version
   ./linpmem  version: 2.1.post4`

I'm building the latest now and will report back.

**Comment by hoyt-harness** [comment]
That was it exactly. I used your binary (I was too anxious to build as it turns out). Thank you!

I'm tagging this issue closed.
