### ISSUE TITLE
Logical Imaging - File Descriptor Limits

### ISSUE THREAD

**Issue by hoyt-harness** [Velocidex/c-aff4#20]
System: Linux Mint 18 Cinnamon 64-bit
Kernel: Linux 4.4.0-119-generic
RAM: 15.6 GiB
linpmem: 3.0.rc1

I ran out of file descriptors pretty quickly. To image a ~1 GB home directory, I obtained about 134 MB of artifacts. This is a typical home directory on Linux Mint 18 with a typical degree of nesting, so nothing edge-case unusual. Here's the output from my application:

  Image user's home directory? [y/n]
  y
  Starting home directory imaging (may take several minutes!)...
  /usr/bin/find: ‘/home/hharness/.cache/dconf’: Permission denied
  2018-04-20 08:40:02 E Can not open file /home/hharness/.config/google-chrome/Default/File 
  System/006/p/03/00000343: Too many open files
  ...

The permissions error was due to not running as root and not something I'm worried about here. The "Too many open files" warnings continue for about 4 MB of text file. I had less trouble imaging /var/log with only errors related to permissions. The system I tested on has a home directory file count of 13,235 (find ~ -type f) and a file-max of 1,609,982 (cat /proc/sys/fs/file-max). Immediately after a reboot, it shows 51,335 open files (lsof | wc -l). That's a lot of open file descriptors available for a typical home directory that only has 13,235 available to find -type f. I can send you the text file of the screen messages if you want (4 MB in size and I'd rather not make it public just yet).

I may be misinterpreting my results from "cat ...file-max" vs "lsof ...wc" as well as the "Too many open files" error. I re-ran the test this way (outside my program) with the same results except those with previous permissions errors weren't excluded because of that this time:

  $ sudo /usr/bin/find ~ -type f | ./thirdparty/linpmem -i @ -o /media/hharness/EVIDENCE/test_lin/img_logical.aff4

I'm sure I'm running the correct version of linpmem now:
  $ ./linpmem --version
  
  ./linpmem  version: 3.0.rc1

It's bound to be something other than file descriptor allocation. I expect at ~16 GB of RAM, that's not the issue, either.

**Comment by scudette** [comment]
This looks like a bug! Thanks for reporting. I will look at it tonight.

**Comment by scudette** [comment]
Should be fixed by the latest pre-release. Thanks for reporting.

**Comment by hoyt-harness** [comment]
Terrific!
