### ISSUE TITLE
Missing configuration check for spdlog

### ISSUE THREAD

**Issue by jtsylve** [Velocidex/c-aff4#28]
spdlog is required to compile, but there's no autoconf check included.

**Comment by scudette** [comment]
We also need the latest git head because the released version in the Ubuntu
repos is too old and actually completely incompatible. I am thinking of
just vendoring that in the tree.

**Comment by jtsylve** [comment]
I support the idea of vendoring as many of the dependencies as possible.  There are quite a few of them and compiling static builds is therefore somewhat tedious.

**Comment by scudette** [comment]
This is now largely solved by docker compose.

**Comment by smaresca** [comment]
@scudette nevertheless, having a check in configure.ac would throw an error msg there preventing the following which I just observed. I'll add it if you'd like.

In file included from ../aff4/lexicon.h:33:0,
                 from aff4_image.cc:16:
../aff4/rdf.h:20:10: fatal error: spdlog/fmt/ostr.h: No such file or directory
 #include <spdlog/fmt/ostr.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by scudette** [comment]
A extra check cant hurt - thanks :-)
