### ISSUE TITLE
C API has no way to control logigng or return error messages

### ISSUE THREAD

**Issue by uckelman-sf** [Velocidex/c-aff4#29]
The C API has no way to control logging or return error messages. It would be a great improvement if instead of having spdlog print to stderr unconditionally, that those messages were collected for use by the caller of libaff4 instead.

I'm willing to submit a patch for this if the libaff4 devs are agreeable.

**Comment by scudette** [comment]
You are right! The C api is not that much used and so it probably lacks some important features like control over logging. Would love to accept patches of course :-).

**Comment by uckelman-sf** [comment]
See PR #66.

**Comment by uckelman-sf** [comment]
Additionally, I'd like to know your thoughts about what it would take to make the C API thread-safe. It looks to me like at present the API as a whole is not thread-safe, not just individual handles.
