### ISSUE TITLE
AFF4_read() unnecessarily copies data

### ISSUE THREAD

**Issue by uckelman-sf** [Velocidex/c-aff4#30]
`AFF4_read` copies data from a `std::string` to the caller-supplied buffer. It would be more efficient if instead the data were read into the caller-supplied buffer directly, to avoid copying.

**Comment by scudette** [comment]
This sounds like a great idea, although the reality is that the data is decompressed anyway so an extra memcpy is probably not going to make a measurable difference in performance. Maybe we can offer an alternative overload of this method?

**Comment by uckelman-sf** [comment]
I've written a patch for this and will be submitting it in the next few days.

**Comment by uckelman-sf** [comment]
Fixed in PR #79.
