### ISSUE TITLE
Build fails with spdlog 1.1.0

### ISSUE THREAD

**Issue by ryandesign** [Velocidex/c-aff4#38]
Hello, building the latest c-aff4 c5c96e6698800555be61bc684d1e0f31b4ca5897 fails if spdlog 1.1.0 is installed:

```
libaff4.cc:554:24: error: no member named 'stderr_color_mt' in namespace 'spdlog'
        return spdlog::stderr_color_mt("aff4");
               ~~~~~~~~^
1 error generated.
make[2]: *** [libaff4.lo] Error 1
```

**Comment by scudette** [comment]
Yep. The instructions say to use 0.11 - c++ dependency management is a nightmare :-(.

https://github.com/Velocidex/c-aff4/blob/master/README.linux#L84

We should probably vendor in as many dependencies as possible.

**Comment by ryandesign** [comment]
> Yep. The instructions say to use 0.11 - c++ dependency management is a nightmare :-(.
> 
> https://github.com/Velocidex/c-aff4/blob/master/README.linux#L84

Hm, that's not obvious. Those instructions seem to be for Linux, and I am not on Linux so I didn't read them, and it is not clarified that all of the versions of the dependencies that are listed there are the only ones that will work.

> We should probably vendor in as many dependencies as possible.

Yes please, or make your code compatible with later versions of the dependencies.

**Comment by scudette** [comment]
Can you try to build with the latest docker setup. I think this will solve all the dependency issues.

**Comment by scudette** [comment]
Closing due to age.

**Comment by ryandesign** [comment]
Your code is still not compatible with spdlog 1.x. Please reopen this issue to track the progress of making your code compatible with spdlog 1.x. Has duplicate #148.

**Comment by ryandesign** [comment]
Or if you don't wish to make your code compatible with spdlog 1.x, you could modify your configuration process so that it gives the user a more pleasant error message if an incompatible version of spdlog is installed (for example using the output of `pkg-config spdlog --modversion`).
