### ISSUE TITLE
winpmem_3.1.rc3.exe does not work correctly on Windows 7 or 10

### ISSUE THREAD

**Issue by jherby2k** [Velocidex/c-aff4#39]
My organization is trying to use the latest `winpmem_3.1.rc3.exe` for the VSM support, but it isn't working for us at all, even without VSM and on Windows 7. On every machine I have tried (all 64-bit, various Windows10 releases - 1803, 1810, 1709) the resulting image is far, far larger than physical memory (tried 8GB and 16GB) - ultimately I've had to kill the capture before the hard drive fills up. We've tried it with `--format raw`, `--format elf`, and with `--output` to stdout and a file.

**Comment by scudette** [comment]
Please see the latest pre-release for a fix.

**Comment by jherby2k** [comment]
Seems fixed, thanks.
