### ISSUE TITLE
Extracting PhysicalMemory from aff4 format

### ISSUE THREAD

**Issue by 4n6ist** [Velocidex/c-aff4#46]
How do I extract raw memory data from aff4 using pmem 3.x?

Whta I tried is here: 

```
> winpmem_3.1.rc6.exe -o win10x86.aff4
```
Succeed to create memory dump with aff4 format
```
> winpmem_3.1.rc6.exe -V win10x86.aff4
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix aff4: <http://aff4.org/Schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix memory: <http://aff4.org/Schema#memory/> .

<aff4://aba09986-2a6b-40e8-9feb-3af9b27137e1/PhysicalMemory>
    aff4:category memory:physical ;
    aff4:stored <aff4://aba09986-2a6b-40e8-9feb-3af9b27137e1> ;
    a aff4:Map .

<aff4://aba09986-2a6b-40e8-9feb-3af9b27137e1/PhysicalMemory/data>
    aff4:chunkSize 32768 ;
    aff4:chunksInSegment 1024 ;
    aff4:compressionMethod <https://www.ietf.org/rfc/rfc1950.txt> ;
    aff4:size 1073205248 ;
    aff4:stored <aff4://aba09986-2a6b-40e8-9feb-3af9b27137e1> ;
    a aff4:ImageStream .
...(snip)
```

```
> winpmem_3.1.rc6.exe -e PhysicalMemory -o win10x86.raw win10x86.aff4
2018-10-30 22:49:39 E Can not specify an export and an output volume at the same time (did you mean --export_dir).
2018-10-30 22:49:39 E Imaging failed with error: -5
```
```
> winpmem_3.1.rc6.exe -e PhysicalMemory --export_dir test win10x86.aff4
> winpmem_3.1.rc6.exe -e PhysicalMemory -D test win10x86.aff4
```
Both commands returns no message and creates no files

winpmem-2.1.post4.exe works -e and -o option to extract stream data. It was very useful for me.

**Comment by scudette** [comment]
Since AFF4 volumes may contain multiple streams, we need a way to specify which streams you want to extract. The -e flag specifies a glob to extract. The glob is applied against the stream URN to select it. So it should be:

winpmem_3.1.rc6.exe -e */PhysicalMemory -D test win10x86.aff4

That said I found a bug with the latest rc6. Let me upload a new RC to fix this.

**Comment by 4n6ist** [comment]
Thanks for your explanation and update!
I have confirmed rc7 extracts PhysicalMemory correctly.

**Comment by scudette** [comment]
Thanks for your feedback. I do agree this is a bit obscure so maybe we should just prepend the volume URN if the extracted arg does not start with aff4:// . I think this behaviour is least surprising.
