### ISSUE TITLE
docker built winpmem.exe is missing the driver

### ISSUE THREAD

**Issue by justfalter** [Velocidex/c-aff4#51]
This is my bad. I removed the strip hook from winpmem's Makefile.am, and opted for using `make install-strip`. Apparently this strips out the driver resource that's plunked onto the end of the file.

**Comment by scudette** [comment]
Yeah I noticed that but I thought we could fix it during release. You just need to cat the drivers to the end of the binary.  This reminds me that there is a small problem with that approach - any authenticode signing will not cover the archive. We can fix that by modifying the PE header to include the archive.

In Go we just encode the binary as a string and compile it in. Maybe thats a better solution.
