### ISSUE TITLE
"make install" keeps appending driver to winpmem.exe

### ISSUE THREAD

**Issue by justfalter** [Velocidex/c-aff4#53]
I noticed that the driver is being appended to winpmem.exe each time that "make install" is called in tools/pmem. The binary will continue to grow and grow. It appears that the "all-local" target, where the appending of the driver occurs, is run each time a "make install" is run. No checking is done to see if the driver has already been appended.

As mentioned [here](https://github.com/Velocidex/c-aff4/issues/51#issuecomment-435524642), authenticode signing will not cover the appended driver, so it may be a good idea to think of other approaches. IIRC, winpmem 2.x included the drivers as a resource, which is included as part of an authenticode signature. Is there a good reason that this can't be done, again?

**Comment by scudette** [comment]
We can include the drivers as a resource again, or simply include it as a static string (which is more portable). I think this will be a good idea.

For now we could maybe add an if statement to the makefile to ensure it is only appended once?

**Comment by scudette** [comment]
This does not happen any more - resources are now embedded as static strings.
