### ISSUE TITLE
Finish removing remove libpcre++ dependency

### ISSUE THREAD

**Issue by justfalter** [Velocidex/c-aff4#62]
I was about to update the docker image to remove the libpcre++ dependency building (in light of #56), when I noticed that the dependency still exists in [linux_pmem.cc](https://github.com/Velocidex/c-aff4/blob/e63ebb5cb5e35db6e04bbb3c52a6705663af47ae/tools/pmem/linux_pmem.cc#L18-L36).

AFAICT, with the changes that had been made in #56, master will probably fail to build linux_pmem.

**Comment by scudette** [comment]
Closing due to age.
