### ISSUE TITLE
Maps with only a single entry are invalid

### ISSUE THREAD

**Issue by blschatz** [Velocidex/c-aff4#93]
Single entry maps use an old broken layout for the map entry. See line
https://github.com/Velocidex/c-aff4/blob/1c463e8078d72b88f3b1016224dbf04d6090b7fb/aff4/aff4_map.cc#L569

The signature is AddRange(map_offset, target_offset,  length, *target)

It should read:   AddRange(0, 0, last_target->Size(), last_target);

**Comment by scudette** [comment]
Fixed by 48110c4353339200965f98f4da9b66213bb35d86  Thanks for reporting :-).
